<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include_once("$curr_dir/lib.php");

	handle_maintenance();

	// drop-downs config
	$lookups = array(
		'sales' => array(
			'user_id' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`id`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`id` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'first_name' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`firstname`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`firstname` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'last_name' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`lastname`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`lastname` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'email' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`email`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`email` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'phone' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`contact_info`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`contact_info` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'address' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`address`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `users`.`id`, `users`.`address` FROM `users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'zone' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`zone`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'zone_fee' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`cost`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'products' => array(
			'category' => array(
				'parent_table' => 'category',
				'parent_pk_field' => 'id',
				'parent_caption' => '`category`.`name`',
				'parent_from' => '`category` LEFT JOIN `sub_cat_2` as sub_cat_21 ON `sub_cat_21`.`code`=`category`.`cat_name` LEFT JOIN `sub_cat` as sub_cat1 ON `sub_cat1`.`sub_category`=`category`.`sub_cat` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `category`.`id`, `category`.`name` FROM `category` LEFT JOIN `sub_cat_2` as sub_cat_21 ON `sub_cat_21`.`code`=`category`.`cat_name` LEFT JOIN `sub_cat` as sub_cat1 ON `sub_cat1`.`sub_category`=`category`.`sub_cat` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'category_id' => array(
				'parent_table' => 'category',
				'parent_pk_field' => 'id',
				'parent_caption' => '`category`.`id`',
				'parent_from' => '`category` LEFT JOIN `sub_cat_2` as sub_cat_21 ON `sub_cat_21`.`code`=`category`.`cat_name` LEFT JOIN `sub_cat` as sub_cat1 ON `sub_cat1`.`sub_category`=`category`.`sub_cat` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `category`.`id`, `category`.`id` FROM `category` LEFT JOIN `sub_cat_2` as sub_cat_21 ON `sub_cat_21`.`code`=`category`.`cat_name` LEFT JOIN `sub_cat` as sub_cat1 ON `sub_cat1`.`sub_category`=`category`.`sub_cat` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_shoes' => array(
				'parent_table' => 'male_shoes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_shoes`.`name`',
				'parent_from' => '`male_shoes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_shoes_id' => array(
				'parent_table' => 'male_shoes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_shoes`.`id`',
				'parent_from' => '`male_shoes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_pants' => array(
				'parent_table' => 'male_pants',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_pants`.`name`',
				'parent_from' => '`male_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_pants_id' => array(
				'parent_table' => 'male_pants',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_pants`.`id`',
				'parent_from' => '`male_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_shirts' => array(
				'parent_table' => 'male_shirts',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_shirts`.`name`',
				'parent_from' => '`male_shirts` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'male_shirts_id' => array(
				'parent_table' => 'male_shirts',
				'parent_pk_field' => 'id',
				'parent_caption' => '`male_shirts`.`id`',
				'parent_from' => '`male_shirts` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_shoes' => array(
				'parent_table' => 'female_shoes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_shoes`.`name`',
				'parent_from' => '`female_shoes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_shoes_id' => array(
				'parent_table' => 'female_shoes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_shoes`.`id`',
				'parent_from' => '`female_shoes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_dresses' => array(
				'parent_table' => 'female_dresses',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_dresses`.`name`',
				'parent_from' => '`female_dresses` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_dresses_id' => array(
				'parent_table' => 'female_dresses',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_dresses`.`id`',
				'parent_from' => '`female_dresses` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_skirts' => array(
				'parent_table' => 'female_skirts',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_skirts`.`name`',
				'parent_from' => '`female_skirts` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_skirts_id' => array(
				'parent_table' => 'female_skirts',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_skirts`.`id`',
				'parent_from' => '`female_skirts` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_pants' => array(
				'parent_table' => 'female_pants',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_pants`.`name`',
				'parent_from' => '`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'female_pants_id' => array(
				'parent_table' => 'female_pants',
				'parent_pk_field' => 'id',
				'parent_caption' => '`female_pants`.`id`',
				'parent_from' => '`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'category' => array(
			'cat_name' => array(
				'parent_table' => 'sub_cat_2',
				'parent_pk_field' => 'code',
				'parent_caption' => '`sub_cat_2`.`cat_name`',
				'parent_from' => '`sub_cat_2` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'sub_cat' => array(
				'parent_table' => 'sub_cat',
				'parent_pk_field' => 'sub_category',
				'parent_caption' => '`sub_cat`.`sub_category`',
				'parent_from' => '`sub_cat` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'code' => array(
				'parent_table' => 'sub_cat_2',
				'parent_pk_field' => 'code',
				'parent_caption' => '`sub_cat_2`.`code`',
				'parent_from' => '`sub_cat_2` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'supplier' => array(
			'drop_off_point' => array(
				'parent_table' => 'drop_off',
				'parent_pk_field' => 'id',
				'parent_caption' => '`drop_off`.`point_name`',
				'parent_from' => '`drop_off` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'drop_off_contact' => array(
				'parent_table' => 'drop_off',
				'parent_pk_field' => 'id',
				'parent_caption' => '`drop_off`.`station_contact`',
				'parent_from' => '`drop_off` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'users' => array(
			'discount' => array(
				'parent_table' => 'coupon',
				'parent_pk_field' => 'coupon_id',
				'parent_caption' => 'IF(CHAR_LENGTH(`coupon`.`coupon_code`) || CHAR_LENGTH(`coupon`.`coupon_id`), CONCAT_WS(\'\', `coupon`.`coupon_code`, `coupon`.`coupon_id`), \'\')',
				'parent_from' => '`coupon` ',
				'filterers' => array(),
				'custom_query' => 'SELECT `coupon`.`coupon_id`, `coupon`.`coupon_code` FROM `coupon` ORDER BY 2',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'coupon_id' => array(
				'parent_table' => 'coupon',
				'parent_pk_field' => 'coupon_id',
				'parent_caption' => '`coupon`.`coupon_id`',
				'parent_from' => '`coupon` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'stock' => array(
			'company_stock_quantity' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'product_name' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'product_id' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'supplier' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'stock_quantity' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'agent' => array(
		),
		'male_shoes' => array(
		),
		'male_pants' => array(
		),
		'male_shirts' => array(
		),
		'female_shoes' => array(
		),
		'female_dresses' => array(
		),
		'female_skirts' => array(
		),
		'female_pants' => array(
		),
		'details' => array(
			'supp_name' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`products`.`supplier`) || CHAR_LENGTH(`products`.`id`), CONCAT_WS(\'\', `products`.`supplier`, `products`.`id`), \'\')',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'sales_id' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => '`sales`.`id`',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'payy_id' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => '`sales`.`pay_id`',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'product_id' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'size' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'branches' => array(
		),
		'agent_monitor' => array(
			'pay_number' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => '`sales`.`pay_id`',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'user_id' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS(\'\',   `users1`.`id`), \'\')',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'sale_date' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => 'if(`sales`.`sales_day`,date_format(`sales`.`sales_day`,\'%m/%d/%Y\'),\'\')',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'user_name' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`sales`.`first_name`) || CHAR_LENGTH(`sales`.`last_name`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`users1`.`firstname`), CONCAT_WS(\'\',   `users1`.`firstname`), \'\'), \'--\', IF(    CHAR_LENGTH(`users1`.`lastname`), CONCAT_WS(\'\',   `users1`.`lastname`), \'\')), \'\')',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'phone' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`users1`.`contact_info`), CONCAT_WS(\'\',   `users1`.`contact_info`), \'\')',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'email' => array(
				'parent_table' => 'sales',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`users1`.`email`), CONCAT_WS(\'\',   `users1`.`email`), \'\')',
				'parent_from' => '`sales` LEFT JOIN `users` as users1 ON `users1`.`id`=`sales`.`user_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'coupon' => array(
		),
		'cart' => array(
		),
		'drop_off' => array(
		),
		'how_to_vendor' => array(
		),
		'how_to_agent' => array(
		),
		'message' => array(
			'user_id' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`id`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'user_name' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`users`.`firstname`) || CHAR_LENGTH(`users`.`lastname`), CONCAT_WS(\'\', `users`.`firstname`, \'  |||   \', `users`.`lastname`), \'\')',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'sales_monitor' => array(
			'product_id' => array(
				'parent_table' => 'details',
				'parent_pk_field' => 'id',
				'parent_caption' => '`details`.`id`',
				'parent_from' => '`details` LEFT JOIN `sales` as sales1 ON `sales1`.`id`=`details`.`sales_id` LEFT JOIN `products` as products1 ON `products1`.`id`=`details`.`product_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'product_name' => array(
				'parent_table' => 'details',
				'parent_pk_field' => 'id',
				'parent_caption' => '`details`.`id`',
				'parent_from' => '`details` LEFT JOIN `sales` as sales1 ON `sales1`.`id`=`details`.`sales_id` LEFT JOIN `products` as products1 ON `products1`.`id`=`details`.`product_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'wishlist' => array(
			'user_id' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`id`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'w_fname' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`firstname`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'w_lname' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`lastname`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'w_email' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`email`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'w_pnumber' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`contact_info`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'product_id' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`id`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'w_product' => array(
				'parent_table' => 'products',
				'parent_pk_field' => 'id',
				'parent_caption' => '`products`.`name`',
				'parent_from' => '`products` LEFT JOIN `category` as category1 ON `category1`.`id`=`products`.`category` LEFT JOIN `male_shoes` as male_shoes1 ON `male_shoes1`.`id`=`products`.`male_shoes` LEFT JOIN `male_pants` as male_pants1 ON `male_pants1`.`id`=`products`.`male_pants` LEFT JOIN `male_shirts` as male_shirts1 ON `male_shirts1`.`id`=`products`.`male_shirts` LEFT JOIN `female_shoes` as female_shoes1 ON `female_shoes1`.`id`=`products`.`female_shoes` LEFT JOIN `female_dresses` as female_dresses1 ON `female_dresses1`.`id`=`products`.`female_dresses` LEFT JOIN `female_skirts` as female_skirts1 ON `female_skirts1`.`id`=`products`.`female_skirts` LEFT JOIN `female_pants` as female_pants1 ON `female_pants1`.`id`=`products`.`female_pants` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'sub_cat' => array(
		),
		'item_rating' => array(
			'userId' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`id`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'rater_name' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`users`.`firstname`) || CHAR_LENGTH(`users`.`lastname`), CONCAT_WS(\'\', `users`.`firstname`, \'--\', `users`.`lastname`), \'\')',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'followers' => array(
			'userid' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => '`users`.`id`',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'f_fname' => array(
				'parent_table' => 'users',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`users`.`firstname`) || CHAR_LENGTH(`users`.`lastname`), CONCAT_WS(\'\', `users`.`firstname`, \'.  .\', `users`.`lastname`), \'\')',
				'parent_from' => '`users` LEFT JOIN `coupon` as coupon1 ON `coupon1`.`coupon_id`=`users`.`discount` LEFT JOIN `coupon` as coupon2 ON `coupon2`.`coupon_id`=`users`.`coupon_id` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'sub_cat_2' => array(
		),
	);

	// XSS prevention
	$xss = new CI_Input(datalist_db_encoding);

	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(from_utf8($_REQUEST['id']));
	$selected_text = from_utf8($_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8($_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm['access'] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = [];

	// search term provided?
	if($search_term) {
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])) {
		foreach($field['filterers'] as $filterer => $filterer_parent) {
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get) {
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']) {
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id) {
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)) {
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']) {
		$qm = []; $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)) {
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)) {
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where) {
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		} elseif($custom_where) {
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		} else {
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = [];
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])) {
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		} else {
			$count_query = '';
		}
	} else {
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id) {
		$combo->SelectedData = $search_id;
	} elseif($selected_text) {
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2) {
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions) {
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		} else {
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>">
			<?php
		}
	} else {
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)) {
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = [];

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text) {
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text)));
		} else {
			/*
			 * in case we have a search term, show matches starting with it first,
			 * followed by those containing it.
			 * build a UNION query for that purpose
			 */
			if($search_term) {
				$query2 = $combo->Query;
				$query1 = str_replace(" like '%{$search_term}%'", " like '{$search_term}%'", $query2);
				$combo->Query = "({$query1}) UNION ({$query2})";
			}

			$eo = ['silentErrors' => true];

			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)) {
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']) {
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>"));
				}

				$prepared_data[] = array('id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1])));
			}
		}

		if(empty($prepared_data)) { $prepared_data[] = array('id' => '', 'text' => to_utf8($Translation['No matches found!'])); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

