<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/branches.php");
	include_once("{$currDir}/branches_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('branches');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'branches';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`branches`.`branch_code`" => "branch_code",
		"`branches`.`country`" => "country",
		"`branches`.`city`" => "city",
		"`branches`.`zonee`" => "zonee",
		"`branches`.`state`" => "state",
		"`branches`.`price`" => "price",
		"`branches`.`zip_code`" => "zip_code",
		"`branches`.`contact`" => "contact",
		"`branches`.`id`" => "id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`branches`.`state`',
		6 => '`branches`.`price`',
		7 => '`branches`.`zip_code`',
		8 => 8,
		9 => '`branches`.`id`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`branches`.`branch_code`" => "branch_code",
		"`branches`.`country`" => "country",
		"`branches`.`city`" => "city",
		"`branches`.`zonee`" => "zonee",
		"`branches`.`state`" => "state",
		"`branches`.`price`" => "price",
		"`branches`.`zip_code`" => "zip_code",
		"`branches`.`contact`" => "contact",
		"`branches`.`id`" => "id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`branches`.`branch_code`" => "Branch Code",
		"`branches`.`country`" => "Station Name",
		"`branches`.`city`" => "City",
		"`branches`.`zonee`" => "Zone",
		"`branches`.`state`" => "Distance",
		"`branches`.`price`" => "Price",
		"`branches`.`zip_code`" => "Delivery Cost",
		"`branches`.`contact`" => "Contact",
		"`branches`.`id`" => "ID",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`branches`.`branch_code`" => "branch_code",
		"`branches`.`country`" => "country",
		"`branches`.`city`" => "city",
		"`branches`.`zonee`" => "zonee",
		"`branches`.`state`" => "state",
		"`branches`.`price`" => "price",
		"`branches`.`zip_code`" => "zip_code",
		"`branches`.`contact`" => "contact",
		"`branches`.`id`" => "id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`branches` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'branches_view.php';
	$x->RedirectAfterInsert = 'branches_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Delivery Branches';
	$x->TableIcon = 'resources/table_icons/Cultures-Origami-icon.png';
	$x->PrimaryKey = '`branches`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 80, 80, 150, ];
	$x->ColCaption = ['Branch Code', 'Station Name', 'City', 'Zone', 'Distance', 'Price', 'Delivery Cost', 'Contact', ];
	$x->ColFieldName = ['branch_code', 'country', 'city', 'zonee', 'state', 'price', 'zip_code', 'contact', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/branches_templateTV.html';
	$x->SelectedTemplate = 'templates/branches_templateTVS.html';
	$x->TemplateDV = 'templates/branches_templateDV.html';
	$x->TemplateDVP = 'templates/branches_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `branches`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='branches' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `branches`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='branches' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`branches`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: branches_init
	$render = true;
	if(function_exists('branches_init')) {
		$args = [];
		$render = branches_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: branches_header
	$headerCode = '';
	if(function_exists('branches_header')) {
		$args = [];
		$headerCode = branches_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: branches_footer
	$footerCode = '';
	if(function_exists('branches_footer')) {
		$args = [];
		$footerCode = branches_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
