<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('category');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'cat_name':
			if(!$id) {
				?>
				$j('#code<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `sub_cat_2`.`code` as 'code', `sub_cat_2`.`cat_name` as 'cat_name' FROM `sub_cat_2`  WHERE `sub_cat_2`.`code`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#code<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['code']))); ?>&nbsp;');
			<?php
			break;


	}

?>