<?php

// Data functions (insert, update, delete, form) for table category

// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

function category_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('category');
	if(!$arrPerm['insert']) return false;

	$data = [
		'name' => Request::val('name', ''),
		'cat_name' => Request::lookup('cat_name', ''),
		'sub_cat' => Request::lookup('sub_cat', ''),
		'code' => Request::lookup('cat_name'),
		'cat_slug' => parseCode('CAT<%%creationTimestamp%%>', true),
	];


	// hook: category_before_insert
	if(function_exists('category_before_insert')) {
		$args = [];
		if(!category_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('category', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('category', $recID, calculated_fields()['category']);

	// hook: category_after_insert
	if(function_exists('category_after_insert')) {
		$res = sql("SELECT * FROM `category` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!category_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('category', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) category_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function category_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function category_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('category', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: category_before_delete
	if(function_exists('category_before_delete')) {
		$args = [];
		if(!category_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: products
	$res = sql("SELECT `id` FROM `category` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `products` WHERE `category`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'products', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'products', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="button" value="' . $Translation['yes'] . '" onClick="window.location = \'category_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="button" value="' . $Translation[ 'no'] . '" onClick="window.location = \'category_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `category` WHERE `id`='{$selected_id}'", $eo);

	// hook: category_after_delete
	if(function_exists('category_after_delete')) {
		$args = [];
		category_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='category' AND `pkValue`='{$selected_id}'", $eo);
}

function category_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('category', $selected_id, 'edit')) return false;

	$data = [
		'name' => Request::val('name', ''),
		'cat_name' => Request::lookup('cat_name', ''),
		'sub_cat' => Request::lookup('sub_cat', ''),
		'code' => Request::lookup('cat_name'),
	];

	// get existing values
	$old_data = getRecord('category', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: category_before_update
	if(function_exists('category_before_update')) {
		$args = ['old_data' => $old_data];
		if(!category_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'category', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="category_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('category', $data['selectedID'], calculated_fields()['category']);

	// hook: category_after_update
	if(function_exists('category_after_update')) {
		$res = sql("SELECT * FROM `category` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!category_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='category' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function category_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('category');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_cat_name = thisOr($_REQUEST['filterer_cat_name'], '');
	$filterer_sub_cat = thisOr($_REQUEST['filterer_sub_cat'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: cat_name
	$combo_cat_name = new DataCombo;
	// combobox: sub_cat
	$combo_sub_cat = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='category' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='category' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `category` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'category_view.php', false);
		}
		$combo_cat_name->SelectedData = $row['cat_name'];
		$combo_sub_cat->SelectedData = $row['sub_cat'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_cat_name->SelectedData = $filterer_cat_name;
		$combo_sub_cat->SelectedData = $filterer_sub_cat;
	}
	$combo_cat_name->HTML = '<span id="cat_name-container' . $rnd1 . '"></span><input type="hidden" name="cat_name" id="cat_name' . $rnd1 . '" value="' . html_attr($combo_cat_name->SelectedData) . '">';
	$combo_cat_name->MatchText = '<span id="cat_name-container-readonly' . $rnd1 . '"></span><input type="hidden" name="cat_name" id="cat_name' . $rnd1 . '" value="' . html_attr($combo_cat_name->SelectedData) . '">';
	$combo_sub_cat->HTML = '<span id="sub_cat-container' . $rnd1 . '"></span><input type="hidden" name="sub_cat" id="sub_cat' . $rnd1 . '" value="' . html_attr($combo_sub_cat->SelectedData) . '">';
	$combo_sub_cat->MatchText = '<span id="sub_cat-container-readonly' . $rnd1 . '"></span><input type="hidden" name="sub_cat" id="sub_cat' . $rnd1 . '" value="' . html_attr($combo_sub_cat->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_cat_name__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['cat_name'] : htmlspecialchars($filterer_cat_name, ENT_QUOTES)); ?>"};
		AppGini.current_sub_cat__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['sub_cat'] : htmlspecialchars($filterer_sub_cat, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(cat_name_reload__RAND__) == 'function') cat_name_reload__RAND__();
				if(typeof(sub_cat_reload__RAND__) == 'function') sub_cat_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function cat_name_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#cat_name-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_cat_name__RAND__.value, t: 'category', f: 'cat_name' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="cat_name"]').val(resp.results[0].id);
							$j('[id=cat_name-container-readonly__RAND__]').html('<span id="cat_name-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_2_view_parent]').hide(); } else { $j('.btn[id=sub_cat_2_view_parent]').show(); }


							if(typeof(cat_name_update_autofills__RAND__) == 'function') cat_name_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'category', f: 'cat_name' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_cat_name__RAND__.value = e.added.id;
				AppGini.current_cat_name__RAND__.text = e.added.text;
				$j('[name="cat_name"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_2_view_parent]').hide(); } else { $j('.btn[id=sub_cat_2_view_parent]').show(); }


				if(typeof(cat_name_update_autofills__RAND__) == 'function') cat_name_update_autofills__RAND__();
			});

			if(!$j("#cat_name-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_cat_name__RAND__.value, t: 'category', f: 'cat_name' },
					success: function(resp) {
						$j('[name="cat_name"]').val(resp.results[0].id);
						$j('[id=cat_name-container-readonly__RAND__]').html('<span id="cat_name-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_2_view_parent]').hide(); } else { $j('.btn[id=sub_cat_2_view_parent]').show(); }

						if(typeof(cat_name_update_autofills__RAND__) == 'function') cat_name_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_cat_name__RAND__.value, t: 'category', f: 'cat_name' },
				success: function(resp) {
					$j('[id=cat_name-container__RAND__], [id=cat_name-container-readonly__RAND__]').html('<span id="cat_name-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_2_view_parent]').hide(); } else { $j('.btn[id=sub_cat_2_view_parent]').show(); }

					if(typeof(cat_name_update_autofills__RAND__) == 'function') cat_name_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function sub_cat_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#sub_cat-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_sub_cat__RAND__.value, t: 'category', f: 'sub_cat' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="sub_cat"]').val(resp.results[0].id);
							$j('[id=sub_cat-container-readonly__RAND__]').html('<span id="sub_cat-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_view_parent]').hide(); } else { $j('.btn[id=sub_cat_view_parent]').show(); }


							if(typeof(sub_cat_update_autofills__RAND__) == 'function') sub_cat_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'category', f: 'sub_cat' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_sub_cat__RAND__.value = e.added.id;
				AppGini.current_sub_cat__RAND__.text = e.added.text;
				$j('[name="sub_cat"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_view_parent]').hide(); } else { $j('.btn[id=sub_cat_view_parent]').show(); }


				if(typeof(sub_cat_update_autofills__RAND__) == 'function') sub_cat_update_autofills__RAND__();
			});

			if(!$j("#sub_cat-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_sub_cat__RAND__.value, t: 'category', f: 'sub_cat' },
					success: function(resp) {
						$j('[name="sub_cat"]').val(resp.results[0].id);
						$j('[id=sub_cat-container-readonly__RAND__]').html('<span id="sub_cat-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_view_parent]').hide(); } else { $j('.btn[id=sub_cat_view_parent]').show(); }

						if(typeof(sub_cat_update_autofills__RAND__) == 'function') sub_cat_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_sub_cat__RAND__.value, t: 'category', f: 'sub_cat' },
				success: function(resp) {
					$j('[id=sub_cat-container__RAND__], [id=sub_cat-container-readonly__RAND__]').html('<span id="sub_cat-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=sub_cat_view_parent]').hide(); } else { $j('.btn[id=sub_cat_view_parent]').show(); }

					if(typeof(sub_cat_update_autofills__RAND__) == 'function') sub_cat_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/category_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/category_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return category_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return category_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return category_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#cat_name').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#cat_name_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#sub_cat').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#sub_cat_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(cat_name)%%>', $combo_cat_name->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(cat_name)%%>', $combo_cat_name->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(cat_name)%%>', urlencode($combo_cat_name->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(sub_cat)%%>', $combo_sub_cat->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(sub_cat)%%>', $combo_sub_cat->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(sub_cat)%%>', urlencode($combo_sub_cat->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('cat_name' => array('sub_cat_2', 'Main Category'), 'sub_cat' => array('sub_cat', 'Sub-category'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cat_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sub_cat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cat_slug)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cat_name)%%>', safe_html($urow['cat_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cat_name)%%>', html_attr($row['cat_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cat_name)%%>', urlencode($urow['cat_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sub_cat)%%>', safe_html($urow['sub_cat']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sub_cat)%%>', html_attr($row['sub_cat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sub_cat)%%>', urlencode($urow['sub_cat']), $templateCode);
		$templateCode = str_replace('<%%VALUE(cat_slug)%%>', safe_html($urow['cat_slug']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cat_slug)%%>', urlencode($urow['cat_slug']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cat_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cat_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sub_cat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sub_cat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(cat_slug)%%>', 'CAT<%%creationTimestamp%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cat_slug)%%>', urlencode('CAT<%%creationTimestamp%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tcat_name_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'category_autofill.php?rnd1=$rnd1&mfk=cat_name&id=' + encodeURIComponent('".addslashes($row['cat_name'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'category_autofill.php?rnd1=$rnd1&mfk=cat_name&id=' + encodeURIComponent(AppGini.current_cat_name{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#cat_name$rnd1').prop('disabled', true); \$j('#cat_nameLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#cat_name$rnd1').prop('disabled', false); " : "\$j('#cat_name$rnd1').prop('disabled', true); ")."\$j('#cat_nameLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#cat_name_caption').length) \$j('#cat_name_caption').click(function() { cat_name_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('category');
	if($selected_id) {
		$jdata = get_joined_record('category', $selected_id);
		if($jdata === false) $jdata = get_defaults('category');
		$rdata = $row;
	}
	$templateCode .= loadView('category-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: category_dv
	if(function_exists('category_dv')) {
		$args=[];
		category_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}