<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/coupon.php");
	include_once("{$currDir}/coupon_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('coupon');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'coupon';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`coupon`.`coupon_id`" => "coupon_id",
		"`coupon`.`coupon_code`" => "coupon_code",
		"`coupon`.`discount`" => "discount",
		"`coupon`.`status`" => "status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`coupon`.`coupon_id`',
		2 => 2,
		3 => '`coupon`.`discount`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`coupon`.`coupon_id`" => "coupon_id",
		"`coupon`.`coupon_code`" => "coupon_code",
		"`coupon`.`discount`" => "discount",
		"`coupon`.`status`" => "status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`coupon`.`coupon_id`" => "ID",
		"`coupon`.`coupon_code`" => "Coupon code",
		"`coupon`.`discount`" => "Discount",
		"`coupon`.`status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`coupon`.`coupon_id`" => "coupon_id",
		"`coupon`.`coupon_code`" => "coupon_code",
		"`coupon`.`discount`" => "discount",
		"`coupon`.`status`" => "status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`coupon` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'coupon_view.php';
	$x->RedirectAfterInsert = 'coupon_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Coupons';
	$x->TableIcon = 'resources/table_icons/Ecommerce-Redeem-icon.png';
	$x->PrimaryKey = '`coupon`.`coupon_id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Coupon code', 'Discount', 'Status', ];
	$x->ColFieldName = ['coupon_code', 'discount', 'status', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/coupon_templateTV.html';
	$x->SelectedTemplate = 'templates/coupon_templateTVS.html';
	$x->TemplateDV = 'templates/coupon_templateDV.html';
	$x->TemplateDVP = 'templates/coupon_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `coupon`.`coupon_id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='coupon' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `coupon`.`coupon_id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='coupon' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`coupon`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: coupon_init
	$render = true;
	if(function_exists('coupon_init')) {
		$args = [];
		$render = coupon_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: coupon_header
	$headerCode = '';
	if(function_exists('coupon_header')) {
		$args = [];
		$headerCode = coupon_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: coupon_footer
	$footerCode = '';
	if(function_exists('coupon_footer')) {
		$args = [];
		$footerCode = coupon_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
