<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/details.php");
	include_once("{$currDir}/details_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('details');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'details';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`details`.`id`" => "id",
		"`details`.`supp_conf`" => "supp_conf",
		"IF(    CHAR_LENGTH(`products1`.`supplier`) || CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`supplier`, `products1`.`id`), '') /* Supp name */" => "supp_name",
		"`details`.`details`" => "details",
		"IF(    CHAR_LENGTH(`sales1`.`id`), CONCAT_WS('',   `sales1`.`id`), '') /* Sales id */" => "sales_id",
		"IF(    CHAR_LENGTH(`sales1`.`pay_id`), CONCAT_WS('',   `sales1`.`pay_id`), '') /* Pay id */" => "payy_id",
		"`details`.`reference_number`" => "reference_number",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Product id */" => "product_id",
		"`details`.`product_name`" => "product_name",
		"`details`.`quantity`" => "quantity",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Size */" => "size",
		"if(`details`.`sales_date`,date_format(`details`.`sales_date`,'%m/%d/%Y'),'')" => "sales_date",
		"`details`.`user_id`" => "user_id",
		"`details`.`recipient_fname`" => "recipient_fname",
		"`details`.`recipient_lname`" => "recipient_lname",
		"`details`.`recipient_contact`" => "recipient_contact",
		"`details`.`recipient_email`" => "recipient_email",
		"`details`.`recipient_address`" => "recipient_address",
		"`details`.`weight`" => "weight",
		"`details`.`length`" => "length",
		"`details`.`width`" => "width",
		"`details`.`height`" => "height",
		"`details`.`price`" => "price",
		"`details`.`pus`" => "pus",
		"`details`.`last_edit`" => "last_edit",
		"`details`.`editor`" => "editor",
		"`details`.`conf_id`" => "conf_id",
		"`details`.`from_branch_id`" => "from_branch_id",
		"`details`.`to_branch_id`" => "to_branch_id",
		"`details`.`type`" => "type",
		"`details`.`status`" => "status",
		"`details`.`total_sales`" => "total_sales",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`details`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`sales1`.`id`',
		6 => '`sales1`.`pay_id`',
		7 => 7,
		8 => '`products1`.`id`',
		9 => 9,
		10 => '`details`.`quantity`',
		11 => '`products1`.`id`',
		12 => '`details`.`sales_date`',
		13 => '`details`.`user_id`',
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => '`details`.`conf_id`',
		28 => '`details`.`from_branch_id`',
		29 => '`details`.`to_branch_id`',
		30 => '`details`.`type`',
		31 => 31,
		32 => 32,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`details`.`id`" => "id",
		"`details`.`supp_conf`" => "supp_conf",
		"IF(    CHAR_LENGTH(`products1`.`supplier`) || CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`supplier`, `products1`.`id`), '') /* Supp name */" => "supp_name",
		"`details`.`details`" => "details",
		"IF(    CHAR_LENGTH(`sales1`.`id`), CONCAT_WS('',   `sales1`.`id`), '') /* Sales id */" => "sales_id",
		"IF(    CHAR_LENGTH(`sales1`.`pay_id`), CONCAT_WS('',   `sales1`.`pay_id`), '') /* Pay id */" => "payy_id",
		"`details`.`reference_number`" => "reference_number",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Product id */" => "product_id",
		"`details`.`product_name`" => "product_name",
		"`details`.`quantity`" => "quantity",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Size */" => "size",
		"if(`details`.`sales_date`,date_format(`details`.`sales_date`,'%m/%d/%Y'),'')" => "sales_date",
		"`details`.`user_id`" => "user_id",
		"`details`.`recipient_fname`" => "recipient_fname",
		"`details`.`recipient_lname`" => "recipient_lname",
		"`details`.`recipient_contact`" => "recipient_contact",
		"`details`.`recipient_email`" => "recipient_email",
		"`details`.`recipient_address`" => "recipient_address",
		"`details`.`weight`" => "weight",
		"`details`.`length`" => "length",
		"`details`.`width`" => "width",
		"`details`.`height`" => "height",
		"`details`.`price`" => "price",
		"`details`.`pus`" => "pus",
		"`details`.`last_edit`" => "last_edit",
		"`details`.`editor`" => "editor",
		"`details`.`conf_id`" => "conf_id",
		"`details`.`from_branch_id`" => "from_branch_id",
		"`details`.`to_branch_id`" => "to_branch_id",
		"`details`.`type`" => "type",
		"`details`.`status`" => "status",
		"`details`.`total_sales`" => "total_sales",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`details`.`id`" => "ID",
		"`details`.`supp_conf`" => "Vendor Order confirmation",
		"IF(    CHAR_LENGTH(`products1`.`supplier`) || CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`supplier`, `products1`.`id`), '') /* Supp name */" => "Supp name",
		"`details`.`details`" => "Product Status",
		"IF(    CHAR_LENGTH(`sales1`.`id`), CONCAT_WS('',   `sales1`.`id`), '') /* Sales id */" => "Sales id",
		"IF(    CHAR_LENGTH(`sales1`.`pay_id`), CONCAT_WS('',   `sales1`.`pay_id`), '') /* Pay id */" => "Pay id",
		"`details`.`reference_number`" => "Tracking Number",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Product id */" => "Product id",
		"`details`.`product_name`" => "Product name",
		"`details`.`quantity`" => "Quantity",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Size */" => "Size",
		"`details`.`sales_date`" => "Sales date",
		"`details`.`user_id`" => "Recipient id",
		"`details`.`recipient_fname`" => "Recipient firstname",
		"`details`.`recipient_lname`" => "Recipient lastname",
		"`details`.`recipient_contact`" => "Phone info",
		"`details`.`recipient_email`" => "Recipient Email",
		"`details`.`recipient_address`" => "Recipient address",
		"`details`.`weight`" => "Weight",
		"`details`.`length`" => "Length",
		"`details`.`width`" => "Width",
		"`details`.`height`" => "Height",
		"`details`.`price`" => "Price",
		"`details`.`pus`" => "Pick Up Station",
		"`details`.`last_edit`" => "Last Edit Date ",
		"`details`.`editor`" => "Editor",
		"`details`.`conf_id`" => "Conf id",
		"`details`.`from_branch_id`" => "From branch id",
		"`details`.`to_branch_id`" => "To branch id",
		"`details`.`type`" => "Type",
		"`details`.`status`" => "Status",
		"`details`.`total_sales`" => "Total sales",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`details`.`id`" => "id",
		"`details`.`supp_conf`" => "supp_conf",
		"IF(    CHAR_LENGTH(`products1`.`supplier`) || CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`supplier`, `products1`.`id`), '') /* Supp name */" => "supp_name",
		"`details`.`details`" => "details",
		"IF(    CHAR_LENGTH(`sales1`.`id`), CONCAT_WS('',   `sales1`.`id`), '') /* Sales id */" => "sales_id",
		"IF(    CHAR_LENGTH(`sales1`.`pay_id`), CONCAT_WS('',   `sales1`.`pay_id`), '') /* Pay id */" => "payy_id",
		"`details`.`reference_number`" => "reference_number",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Product id */" => "product_id",
		"`details`.`product_name`" => "product_name",
		"`details`.`quantity`" => "quantity",
		"IF(    CHAR_LENGTH(`products1`.`id`), CONCAT_WS('',   `products1`.`id`), '') /* Size */" => "size",
		"if(`details`.`sales_date`,date_format(`details`.`sales_date`,'%m/%d/%Y'),'')" => "sales_date",
		"`details`.`user_id`" => "user_id",
		"`details`.`recipient_fname`" => "recipient_fname",
		"`details`.`recipient_lname`" => "recipient_lname",
		"`details`.`recipient_contact`" => "recipient_contact",
		"`details`.`recipient_email`" => "recipient_email",
		"`details`.`recipient_address`" => "recipient_address",
		"`details`.`weight`" => "weight",
		"`details`.`length`" => "length",
		"`details`.`width`" => "width",
		"`details`.`height`" => "height",
		"`details`.`price`" => "price",
		"`details`.`pus`" => "pus",
		"`details`.`last_edit`" => "last_edit",
		"`details`.`editor`" => "editor",
		"`details`.`conf_id`" => "conf_id",
		"`details`.`from_branch_id`" => "from_branch_id",
		"`details`.`to_branch_id`" => "to_branch_id",
		"`details`.`type`" => "type",
		"`details`.`status`" => "status",
		"`details`.`total_sales`" => "total_sales",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['sales_id' => 'Sales id', 'product_id' => 'Product id', ];

	$x->QueryFrom = "`details` LEFT JOIN `sales` as sales1 ON `sales1`.`id`=`details`.`sales_id` LEFT JOIN `products` as products1 ON `products1`.`id`=`details`.`product_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'details_view.php';
	$x->RedirectAfterInsert = 'details_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Order Details';
	$x->TableIcon = 'resources/table_icons/increase-icon.png';
	$x->PrimaryKey = '`details`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 80, 150, 150, 150, ];
	$x->ColCaption = ['Vendor Order confirmation', 'Supp name', 'Product Status', 'Sales id', 'Pay id', 'Tracking Number', 'Product id', 'Product name', 'Quantity', 'Size', 'Sales date', 'Recipient id', 'Recipient firstname', 'Recipient lastname', 'Phone info', 'Recipient Email', 'Recipient address', 'Weight', 'Length', 'Width', 'Height', 'Price', 'Pick Up Station', 'Last Edit Date ', 'Editor', ];
	$x->ColFieldName = ['supp_conf', 'supp_name', 'details', 'sales_id', 'payy_id', 'reference_number', 'product_id', 'product_name', 'quantity', 'size', 'sales_date', 'user_id', 'recipient_fname', 'recipient_lname', 'recipient_contact', 'recipient_email', 'recipient_address', 'weight', 'length', 'width', 'height', 'price', 'pus', 'last_edit', 'editor', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/details_templateTV.html';
	$x->SelectedTemplate = 'templates/details_templateTVS.html';
	$x->TemplateDV = 'templates/details_templateDV.html';
	$x->TemplateDVP = 'templates/details_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `details`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='details' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `details`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='details' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`details`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: details_init
	$render = true;
	if(function_exists('details_init')) {
		$args = [];
		$render = details_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: details_header
	$headerCode = '';
	if(function_exists('details_header')) {
		$args = [];
		$headerCode = details_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: details_footer
	$footerCode = '';
	if(function_exists('details_footer')) {
		$args = [];
		$footerCode = details_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
