<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/how_to_agent.php");
	include_once("{$currDir}/how_to_agent_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('how_to_agent');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'how_to_agent';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`how_to_agent`.`id`" => "id",
		"`how_to_agent`.`how_to_1`" => "how_to_1",
		"`how_to_agent`.`how_to_2`" => "how_to_2",
		"`how_to_agent`.`how_to_3`" => "how_to_3",
		"`how_to_agent`.`how_to_4`" => "how_to_4",
		"`how_to_agent`.`how_to_5`" => "how_to_5",
		"`how_to_agent`.`how_to_6`" => "how_to_6",
		"`how_to_agent`.`how_to_7`" => "how_to_7",
		"`how_to_agent`.`how_to_8`" => "how_to_8",
		"`how_to_agent`.`how_to_9`" => "how_to_9",
		"`how_to_agent`.`how_to_10`" => "how_to_10",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`how_to_agent`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`how_to_agent`.`id`" => "id",
		"`how_to_agent`.`how_to_1`" => "how_to_1",
		"`how_to_agent`.`how_to_2`" => "how_to_2",
		"`how_to_agent`.`how_to_3`" => "how_to_3",
		"`how_to_agent`.`how_to_4`" => "how_to_4",
		"`how_to_agent`.`how_to_5`" => "how_to_5",
		"`how_to_agent`.`how_to_6`" => "how_to_6",
		"`how_to_agent`.`how_to_7`" => "how_to_7",
		"`how_to_agent`.`how_to_8`" => "how_to_8",
		"`how_to_agent`.`how_to_9`" => "how_to_9",
		"`how_to_agent`.`how_to_10`" => "how_to_10",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`how_to_agent`.`id`" => "ID",
		"`how_to_agent`.`how_to_1`" => "How to 1",
		"`how_to_agent`.`how_to_2`" => "How to 2",
		"`how_to_agent`.`how_to_3`" => "How to 3",
		"`how_to_agent`.`how_to_4`" => "How to 4",
		"`how_to_agent`.`how_to_5`" => "How to 5",
		"`how_to_agent`.`how_to_6`" => "How to 6",
		"`how_to_agent`.`how_to_7`" => "How to 7",
		"`how_to_agent`.`how_to_8`" => "How to 8",
		"`how_to_agent`.`how_to_9`" => "How to 9",
		"`how_to_agent`.`how_to_10`" => "How to 10",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`how_to_agent`.`id`" => "id",
		"`how_to_agent`.`how_to_1`" => "how_to_1",
		"`how_to_agent`.`how_to_2`" => "how_to_2",
		"`how_to_agent`.`how_to_3`" => "how_to_3",
		"`how_to_agent`.`how_to_4`" => "how_to_4",
		"`how_to_agent`.`how_to_5`" => "how_to_5",
		"`how_to_agent`.`how_to_6`" => "how_to_6",
		"`how_to_agent`.`how_to_7`" => "how_to_7",
		"`how_to_agent`.`how_to_8`" => "how_to_8",
		"`how_to_agent`.`how_to_9`" => "how_to_9",
		"`how_to_agent`.`how_to_10`" => "how_to_10",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`how_to_agent` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'how_to_agent_view.php';
	$x->RedirectAfterInsert = 'how_to_agent_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Agent Guide';
	$x->TableIcon = 'resources/table_icons/Receipt-3-icon.png';
	$x->PrimaryKey = '`how_to_agent`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['How to 1', 'How to 2', 'How to 3', 'How to 4', 'How to 5', 'How to 6', 'How to 7', 'How to 8', 'How to 9', 'How to 10', ];
	$x->ColFieldName = ['how_to_1', 'how_to_2', 'how_to_3', 'how_to_4', 'how_to_5', 'how_to_6', 'how_to_7', 'how_to_8', 'how_to_9', 'how_to_10', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/how_to_agent_templateTV.html';
	$x->SelectedTemplate = 'templates/how_to_agent_templateTVS.html';
	$x->TemplateDV = 'templates/how_to_agent_templateDV.html';
	$x->TemplateDVP = 'templates/how_to_agent_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `how_to_agent`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='how_to_agent' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `how_to_agent`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='how_to_agent' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`how_to_agent`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: how_to_agent_init
	$render = true;
	if(function_exists('how_to_agent_init')) {
		$args = [];
		$render = how_to_agent_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: how_to_agent_header
	$headerCode = '';
	if(function_exists('how_to_agent_header')) {
		$args = [];
		$headerCode = how_to_agent_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: how_to_agent_footer
	$footerCode = '';
	if(function_exists('how_to_agent_footer')) {
		$args = [];
		$footerCode = how_to_agent_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
