<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/item_rating.php");
	include_once("{$currDir}/item_rating_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('item_rating');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'item_rating';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`item_rating`.`ratingId`" => "ratingId",
		"`item_rating`.`itemId`" => "itemId",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* Rater id */" => "userId",
		"IF(    CHAR_LENGTH(`users1`.`firstname`) || CHAR_LENGTH(`users1`.`lastname`), CONCAT_WS('',   `users1`.`firstname`, '--', `users1`.`lastname`), '') /* Rater name */" => "rater_name",
		"`item_rating`.`ratingNumber`" => "ratingNumber",
		"`item_rating`.`title`" => "title",
		"`item_rating`.`comments`" => "comments",
		"`item_rating`.`created`" => "created",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`item_rating`.`ratingId`',
		2 => '`item_rating`.`itemId`',
		3 => '`users1`.`id`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`item_rating`.`ratingId`" => "ratingId",
		"`item_rating`.`itemId`" => "itemId",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* Rater id */" => "userId",
		"IF(    CHAR_LENGTH(`users1`.`firstname`) || CHAR_LENGTH(`users1`.`lastname`), CONCAT_WS('',   `users1`.`firstname`, '--', `users1`.`lastname`), '') /* Rater name */" => "rater_name",
		"`item_rating`.`ratingNumber`" => "ratingNumber",
		"`item_rating`.`title`" => "title",
		"`item_rating`.`comments`" => "comments",
		"`item_rating`.`created`" => "created",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`item_rating`.`ratingId`" => "rating Id",
		"`item_rating`.`itemId`" => "Item Slug code",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* Rater id */" => "Rater id",
		"IF(    CHAR_LENGTH(`users1`.`firstname`) || CHAR_LENGTH(`users1`.`lastname`), CONCAT_WS('',   `users1`.`firstname`, '--', `users1`.`lastname`), '') /* Rater name */" => "Rater name",
		"`item_rating`.`ratingNumber`" => "Rated stars",
		"`item_rating`.`title`" => "Items",
		"`item_rating`.`comments`" => "Comments",
		"`item_rating`.`created`" => "Rated On",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`item_rating`.`ratingId`" => "ratingId",
		"`item_rating`.`itemId`" => "itemId",
		"IF(    CHAR_LENGTH(`users1`.`id`), CONCAT_WS('',   `users1`.`id`), '') /* Rater id */" => "userId",
		"IF(    CHAR_LENGTH(`users1`.`firstname`) || CHAR_LENGTH(`users1`.`lastname`), CONCAT_WS('',   `users1`.`firstname`, '--', `users1`.`lastname`), '') /* Rater name */" => "rater_name",
		"`item_rating`.`ratingNumber`" => "ratingNumber",
		"`item_rating`.`title`" => "title",
		"`item_rating`.`comments`" => "comments",
		"`item_rating`.`created`" => "created",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['userId' => 'Rater id', ];

	$x->QueryFrom = "`item_rating` LEFT JOIN `users` as users1 ON `users1`.`id`=`item_rating`.`userId` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'item_rating_view.php';
	$x->RedirectAfterInsert = 'item_rating_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Item rating';
	$x->TableIcon = 'resources/table_icons/award_star_gold_1.png';
	$x->PrimaryKey = '`item_rating`.`ratingId`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Item Slug code', 'Rater id', 'Rater name', 'Rated stars', 'Items', 'Comments', 'Rated On', ];
	$x->ColFieldName = ['itemId', 'userId', 'rater_name', 'ratingNumber', 'title', 'comments', 'created', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/item_rating_templateTV.html';
	$x->SelectedTemplate = 'templates/item_rating_templateTVS.html';
	$x->TemplateDV = 'templates/item_rating_templateDV.html';
	$x->TemplateDVP = 'templates/item_rating_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `item_rating`.`ratingId`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='item_rating' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `item_rating`.`ratingId`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='item_rating' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`item_rating`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: item_rating_init
	$render = true;
	if(function_exists('item_rating_init')) {
		$args = [];
		$render = item_rating_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: item_rating_header
	$headerCode = '';
	if(function_exists('item_rating_header')) {
		$args = [];
		$headerCode = item_rating_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: item_rating_footer
	$footerCode = '';
	if(function_exists('item_rating_footer')) {
		$args = [];
		$footerCode = item_rating_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
