<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/sales_monitor.php");
	include_once("{$currDir}/sales_monitor_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('sales_monitor');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'sales_monitor';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`sales_monitor`.`id`" => "id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product id */" => "product_id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product name */" => "product_name",
		"`sales_monitor`.`total_sale`" => "total_sale",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`sales_monitor`.`id`',
		2 => '`details1`.`id`',
		3 => '`details1`.`id`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`sales_monitor`.`id`" => "id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product id */" => "product_id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product name */" => "product_name",
		"`sales_monitor`.`total_sale`" => "total_sale",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`sales_monitor`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product id */" => "Product id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product name */" => "Product name",
		"`sales_monitor`.`total_sale`" => "Total sale",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`sales_monitor`.`id`" => "id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product id */" => "product_id",
		"IF(    CHAR_LENGTH(`details1`.`id`), CONCAT_WS('',   `details1`.`id`), '') /* Product name */" => "product_name",
		"`sales_monitor`.`total_sale`" => "total_sale",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['product_id' => 'Product id', ];

	$x->QueryFrom = "`sales_monitor` LEFT JOIN `details` as details1 ON `details1`.`id`=`sales_monitor`.`product_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'sales_monitor_view.php';
	$x->RedirectAfterInsert = 'sales_monitor_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Sales monitor';
	$x->TableIcon = 'resources/table_icons/bar-chart-icon.png';
	$x->PrimaryKey = '`sales_monitor`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Product id', 'Product name', 'Total sale', ];
	$x->ColFieldName = ['product_id', 'product_name', 'total_sale', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/sales_monitor_templateTV.html';
	$x->SelectedTemplate = 'templates/sales_monitor_templateTVS.html';
	$x->TemplateDV = 'templates/sales_monitor_templateDV.html';
	$x->TemplateDVP = 'templates/sales_monitor_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `sales_monitor`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='sales_monitor' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `sales_monitor`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='sales_monitor' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`sales_monitor`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: sales_monitor_init
	$render = true;
	if(function_exists('sales_monitor_init')) {
		$args = [];
		$render = sales_monitor_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: sales_monitor_header
	$headerCode = '';
	if(function_exists('sales_monitor_header')) {
		$args = [];
		$headerCode = sales_monitor_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: sales_monitor_footer
	$footerCode = '';
	if(function_exists('sales_monitor_footer')) {
		$args = [];
		$footerCode = sales_monitor_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
