<?php

// Data functions (insert, update, delete, form) for table about_us

// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

function about_us_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('about_us');
	if(!$arrPerm['insert']) return false;

	$data = [
		'main_head' => Request::val('main_head', ''),
		'main_head_content' => br2nl(Request::val('main_head_content', '')),
		'a_head' => Request::val('a_head', ''),
		'a_subhead' => Request::val('a_subhead', ''),
		'a_content' => br2nl(Request::val('a_content', '')),
		'b_head' => Request::val('b_head', ''),
		'b_subhead' => Request::val('b_subhead', ''),
		'b_content' => br2nl(Request::val('b_content', '')),
		'c_head' => Request::val('c_head', ''),
		'c_subhead' => Request::val('c_subhead', ''),
		'c_content' => br2nl(Request::val('c_content', '')),
		'a2_head' => Request::val('a2_head', ''),
		'a2_content' => br2nl(Request::val('a2_content', '')),
		'a2_head_1' => Request::val('a2_head_1', ''),
		'a2_content_1' => br2nl(Request::val('a2_content_1', '')),
		'a2_head_2' => Request::val('a2_head_2', ''),
		'a2_content_2' => br2nl(Request::val('a2_content_2', '')),
		'a2_head_3' => Request::val('a2_head_3', ''),
		'a2_content_3' => br2nl(Request::val('a2_content_3', '')),
		'a3_mainhead' => Request::val('a3_mainhead', ''),
		'a3_head' => Request::val('a3_head', ''),
		'a3_content' => Request::val('a3_content', ''),
		'a3_head_1' => Request::val('a3_head_1', ''),
		'a3_content_1' => Request::val('a3_content_1', ''),
		'a3_head_2' => Request::val('a3_head_2', ''),
		'a3_content_2' => Request::val('a3_content_2', ''),
		'a3_head_3' => Request::val('a3_head_3', ''),
		'a3_content_3' => Request::val('a3_content_3', ''),
	];


	// hook: about_us_before_insert
	if(function_exists('about_us_before_insert')) {
		$args = [];
		if(!about_us_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('about_us', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('about_us', $recID, calculated_fields()['about_us']);

	// hook: about_us_after_insert
	if(function_exists('about_us_after_insert')) {
		$res = sql("SELECT * FROM `about_us` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!about_us_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('about_us', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) about_us_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function about_us_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function about_us_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('about_us', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: about_us_before_delete
	if(function_exists('about_us_before_delete')) {
		$args = [];
		if(!about_us_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `about_us` WHERE `id`='{$selected_id}'", $eo);

	// hook: about_us_after_delete
	if(function_exists('about_us_after_delete')) {
		$args = [];
		about_us_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='about_us' AND `pkValue`='{$selected_id}'", $eo);
}

function about_us_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('about_us', $selected_id, 'edit')) return false;

	$data = [
		'main_head' => Request::val('main_head', ''),
		'main_head_content' => br2nl(Request::val('main_head_content', '')),
		'a_head' => Request::val('a_head', ''),
		'a_subhead' => Request::val('a_subhead', ''),
		'a_content' => br2nl(Request::val('a_content', '')),
		'b_head' => Request::val('b_head', ''),
		'b_subhead' => Request::val('b_subhead', ''),
		'b_content' => br2nl(Request::val('b_content', '')),
		'c_head' => Request::val('c_head', ''),
		'c_subhead' => Request::val('c_subhead', ''),
		'c_content' => br2nl(Request::val('c_content', '')),
		'a2_head' => Request::val('a2_head', ''),
		'a2_content' => br2nl(Request::val('a2_content', '')),
		'a2_head_1' => Request::val('a2_head_1', ''),
		'a2_content_1' => br2nl(Request::val('a2_content_1', '')),
		'a2_head_2' => Request::val('a2_head_2', ''),
		'a2_content_2' => br2nl(Request::val('a2_content_2', '')),
		'a2_head_3' => Request::val('a2_head_3', ''),
		'a2_content_3' => br2nl(Request::val('a2_content_3', '')),
		'a3_mainhead' => Request::val('a3_mainhead', ''),
		'a3_head' => Request::val('a3_head', ''),
		'a3_content' => Request::val('a3_content', ''),
		'a3_head_1' => Request::val('a3_head_1', ''),
		'a3_content_1' => Request::val('a3_content_1', ''),
		'a3_head_2' => Request::val('a3_head_2', ''),
		'a3_content_2' => Request::val('a3_content_2', ''),
		'a3_head_3' => Request::val('a3_head_3', ''),
		'a3_content_3' => Request::val('a3_content_3', ''),
	];

	// get existing values
	$old_data = getRecord('about_us', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: about_us_before_update
	if(function_exists('about_us_before_update')) {
		$args = ['old_data' => $old_data];
		if(!about_us_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'about_us', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="about_us_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('about_us', $data['selectedID'], calculated_fields()['about_us']);

	// hook: about_us_after_update
	if(function_exists('about_us_after_update')) {
		$res = sql("SELECT * FROM `about_us` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!about_us_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='about_us' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function about_us_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('about_us');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='about_us' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='about_us' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `about_us` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'about_us_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/about_us_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/about_us_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'About u details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return about_us_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return about_us_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return about_us_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#main_head').replaceWith('<div class=\"form-control-static\" id=\"main_head\">' + (jQuery('#main_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#main_head_content').replaceWith('<div class=\"form-control-static\" id=\"main_head_content\">' + (jQuery('#main_head_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a_head').replaceWith('<div class=\"form-control-static\" id=\"a_head\">' + (jQuery('#a_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a_subhead').replaceWith('<div class=\"form-control-static\" id=\"a_subhead\">' + (jQuery('#a_subhead').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a_content').replaceWith('<div class=\"form-control-static\" id=\"a_content\">' + (jQuery('#a_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#b_head').replaceWith('<div class=\"form-control-static\" id=\"b_head\">' + (jQuery('#b_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#b_subhead').replaceWith('<div class=\"form-control-static\" id=\"b_subhead\">' + (jQuery('#b_subhead').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#b_content').replaceWith('<div class=\"form-control-static\" id=\"b_content\">' + (jQuery('#b_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#c_head').replaceWith('<div class=\"form-control-static\" id=\"c_head\">' + (jQuery('#c_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#c_subhead').replaceWith('<div class=\"form-control-static\" id=\"c_subhead\">' + (jQuery('#c_subhead').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#c_content').replaceWith('<div class=\"form-control-static\" id=\"c_content\">' + (jQuery('#c_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_head').replaceWith('<div class=\"form-control-static\" id=\"a2_head\">' + (jQuery('#a2_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_content').replaceWith('<div class=\"form-control-static\" id=\"a2_content\">' + (jQuery('#a2_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_head_1').replaceWith('<div class=\"form-control-static\" id=\"a2_head_1\">' + (jQuery('#a2_head_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_content_1').replaceWith('<div class=\"form-control-static\" id=\"a2_content_1\">' + (jQuery('#a2_content_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_head_2').replaceWith('<div class=\"form-control-static\" id=\"a2_head_2\">' + (jQuery('#a2_head_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_content_2').replaceWith('<div class=\"form-control-static\" id=\"a2_content_2\">' + (jQuery('#a2_content_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_head_3').replaceWith('<div class=\"form-control-static\" id=\"a2_head_3\">' + (jQuery('#a2_head_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a2_content_3').replaceWith('<div class=\"form-control-static\" id=\"a2_content_3\">' + (jQuery('#a2_content_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_mainhead').replaceWith('<div class=\"form-control-static\" id=\"a3_mainhead\">' + (jQuery('#a3_mainhead').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_head').replaceWith('<div class=\"form-control-static\" id=\"a3_head\">' + (jQuery('#a3_head').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_content').replaceWith('<div class=\"form-control-static\" id=\"a3_content\">' + (jQuery('#a3_content').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_head_1').replaceWith('<div class=\"form-control-static\" id=\"a3_head_1\">' + (jQuery('#a3_head_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_content_1').replaceWith('<div class=\"form-control-static\" id=\"a3_content_1\">' + (jQuery('#a3_content_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_head_2').replaceWith('<div class=\"form-control-static\" id=\"a3_head_2\">' + (jQuery('#a3_head_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_content_2').replaceWith('<div class=\"form-control-static\" id=\"a3_content_2\">' + (jQuery('#a3_content_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_head_3').replaceWith('<div class=\"form-control-static\" id=\"a3_head_3\">' + (jQuery('#a3_head_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#a3_content_3').replaceWith('<div class=\"form-control-static\" id=\"a3_content_3\">' + (jQuery('#a3_content_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(main_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(main_head_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(section_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a_subhead)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(b_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(b_subhead)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(b_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(c_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(c_subhead)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(c_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(section_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_head_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_content_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_head_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_content_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_head_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a2_content_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(section_4)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_mainhead)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_head)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_content)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_head_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_content_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_head_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_content_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_head_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(a3_content_3)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(main_head)%%>', safe_html($urow['main_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(main_head)%%>', html_attr($row['main_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(main_head)%%>', urlencode($urow['main_head']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(main_head_content)%%>', safe_html($urow['main_head_content']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(main_head_content)%%>', safe_html($urow['main_head_content'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(main_head_content)%%>', urlencode($urow['main_head_content']), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_2)%%>', safe_html($urow['section_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_2)%%>', urlencode($urow['section_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a_head)%%>', safe_html($urow['a_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a_head)%%>', html_attr($row['a_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a_head)%%>', urlencode($urow['a_head']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a_subhead)%%>', safe_html($urow['a_subhead']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a_subhead)%%>', html_attr($row['a_subhead']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a_subhead)%%>', urlencode($urow['a_subhead']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(a_content)%%>', safe_html($urow['a_content']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(a_content)%%>', safe_html($urow['a_content'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(a_content)%%>', urlencode($urow['a_content']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(b_head)%%>', safe_html($urow['b_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(b_head)%%>', html_attr($row['b_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(b_head)%%>', urlencode($urow['b_head']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(b_subhead)%%>', safe_html($urow['b_subhead']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(b_subhead)%%>', html_attr($row['b_subhead']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(b_subhead)%%>', urlencode($urow['b_subhead']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(b_content)%%>', safe_html($urow['b_content']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(b_content)%%>', safe_html($urow['b_content'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(b_content)%%>', urlencode($urow['b_content']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(c_head)%%>', safe_html($urow['c_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(c_head)%%>', html_attr($row['c_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(c_head)%%>', urlencode($urow['c_head']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(c_subhead)%%>', safe_html($urow['c_subhead']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(c_subhead)%%>', html_attr($row['c_subhead']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(c_subhead)%%>', urlencode($urow['c_subhead']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(c_content)%%>', safe_html($urow['c_content']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(c_content)%%>', safe_html($urow['c_content'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(c_content)%%>', urlencode($urow['c_content']), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_3)%%>', safe_html($urow['section_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_3)%%>', urlencode($urow['section_3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a2_head)%%>', safe_html($urow['a2_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a2_head)%%>', html_attr($row['a2_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head)%%>', urlencode($urow['a2_head']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(a2_content)%%>', safe_html($urow['a2_content']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(a2_content)%%>', safe_html($urow['a2_content'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(a2_content)%%>', urlencode($urow['a2_content']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a2_head_1)%%>', safe_html($urow['a2_head_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a2_head_1)%%>', html_attr($row['a2_head_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_1)%%>', urlencode($urow['a2_head_1']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(a2_content_1)%%>', safe_html($urow['a2_content_1']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(a2_content_1)%%>', safe_html($urow['a2_content_1'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(a2_content_1)%%>', urlencode($urow['a2_content_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a2_head_2)%%>', safe_html($urow['a2_head_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a2_head_2)%%>', html_attr($row['a2_head_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_2)%%>', urlencode($urow['a2_head_2']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(a2_content_2)%%>', safe_html($urow['a2_content_2']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(a2_content_2)%%>', safe_html($urow['a2_content_2'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(a2_content_2)%%>', urlencode($urow['a2_content_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a2_head_3)%%>', safe_html($urow['a2_head_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a2_head_3)%%>', html_attr($row['a2_head_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_3)%%>', urlencode($urow['a2_head_3']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(a2_content_3)%%>', safe_html($urow['a2_content_3']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(a2_content_3)%%>', safe_html($urow['a2_content_3'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(a2_content_3)%%>', urlencode($urow['a2_content_3']), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_4)%%>', safe_html($urow['section_4']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_4)%%>', urlencode($urow['section_4']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_mainhead)%%>', safe_html($urow['a3_mainhead']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_mainhead)%%>', html_attr($row['a3_mainhead']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_mainhead)%%>', urlencode($urow['a3_mainhead']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_head)%%>', safe_html($urow['a3_head']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_head)%%>', html_attr($row['a3_head']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head)%%>', urlencode($urow['a3_head']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_content)%%>', safe_html($urow['a3_content']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_content)%%>', html_attr($row['a3_content']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content)%%>', urlencode($urow['a3_content']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_head_1)%%>', safe_html($urow['a3_head_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_head_1)%%>', html_attr($row['a3_head_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_1)%%>', urlencode($urow['a3_head_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_content_1)%%>', safe_html($urow['a3_content_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_content_1)%%>', html_attr($row['a3_content_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_1)%%>', urlencode($urow['a3_content_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_head_2)%%>', safe_html($urow['a3_head_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_head_2)%%>', html_attr($row['a3_head_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_2)%%>', urlencode($urow['a3_head_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_content_2)%%>', safe_html($urow['a3_content_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_content_2)%%>', html_attr($row['a3_content_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_2)%%>', urlencode($urow['a3_content_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_head_3)%%>', safe_html($urow['a3_head_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_head_3)%%>', html_attr($row['a3_head_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_3)%%>', urlencode($urow['a3_head_3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(a3_content_3)%%>', safe_html($urow['a3_content_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(a3_content_3)%%>', html_attr($row['a3_content_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_3)%%>', urlencode($urow['a3_content_3']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(main_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(main_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(main_head_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(main_head_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a_subhead)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a_subhead)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(b_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(b_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(b_subhead)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(b_subhead)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(b_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(b_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(c_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(c_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(c_subhead)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(c_subhead)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(c_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(c_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_head_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_content_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_content_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_head_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_content_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_content_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_head_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_head_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a2_content_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a2_content_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(section_4)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(section_4)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_mainhead)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_mainhead)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_head)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_content)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_head_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_content_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_head_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_content_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_head_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_head_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(a3_content_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(a3_content_3)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('about_us');
	if($selected_id) {
		$jdata = get_joined_record('about_us', $selected_id);
		if($jdata === false) $jdata = get_defaults('about_us');
		$rdata = $row;
	}
	$templateCode .= loadView('about_us-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: about_us_dv
	if(function_exists('about_us_dv')) {
		$args=[];
		about_us_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}