<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/terms_conditions.php");
	include_once("{$currDir}/terms_conditions_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('terms_conditions');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'terms_conditions';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`terms_conditions`.`id`" => "id",
		"`terms_conditions`.`main_head`" => "main_head",
		"`terms_conditions`.`main_head_content`" => "main_head_content",
		"`terms_conditions`.`sub_head1`" => "sub_head1",
		"`terms_conditions`.`head_1`" => "head_1",
		"`terms_conditions`.`sub_head2`" => "sub_head2",
		"`terms_conditions`.`head_2`" => "head_2",
		"`terms_conditions`.`sub_head3`" => "sub_head3",
		"`terms_conditions`.`head_3`" => "head_3",
		"`terms_conditions`.`sub_head4`" => "sub_head4",
		"`terms_conditions`.`head_4`" => "head_4",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`terms_conditions`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`terms_conditions`.`id`" => "id",
		"`terms_conditions`.`main_head`" => "main_head",
		"`terms_conditions`.`main_head_content`" => "main_head_content",
		"`terms_conditions`.`sub_head1`" => "sub_head1",
		"`terms_conditions`.`head_1`" => "head_1",
		"`terms_conditions`.`sub_head2`" => "sub_head2",
		"`terms_conditions`.`head_2`" => "head_2",
		"`terms_conditions`.`sub_head3`" => "sub_head3",
		"`terms_conditions`.`head_3`" => "head_3",
		"`terms_conditions`.`sub_head4`" => "sub_head4",
		"`terms_conditions`.`head_4`" => "head_4",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`terms_conditions`.`id`" => "ID",
		"`terms_conditions`.`main_head`" => "Main head",
		"`terms_conditions`.`main_head_content`" => "Main head content",
		"`terms_conditions`.`sub_head1`" => "Sub head1",
		"`terms_conditions`.`head_1`" => "Head 1 Content",
		"`terms_conditions`.`sub_head2`" => "Sub head2",
		"`terms_conditions`.`head_2`" => "Head 2 content",
		"`terms_conditions`.`sub_head3`" => "Sub head3",
		"`terms_conditions`.`head_3`" => "Head 3 content",
		"`terms_conditions`.`sub_head4`" => "Sub head4",
		"`terms_conditions`.`head_4`" => "Head 4 content",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`terms_conditions`.`id`" => "id",
		"`terms_conditions`.`main_head`" => "main_head",
		"`terms_conditions`.`main_head_content`" => "main_head_content",
		"`terms_conditions`.`sub_head1`" => "sub_head1",
		"`terms_conditions`.`head_1`" => "head_1",
		"`terms_conditions`.`sub_head2`" => "sub_head2",
		"`terms_conditions`.`head_2`" => "head_2",
		"`terms_conditions`.`sub_head3`" => "sub_head3",
		"`terms_conditions`.`head_3`" => "head_3",
		"`terms_conditions`.`sub_head4`" => "sub_head4",
		"`terms_conditions`.`head_4`" => "head_4",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`terms_conditions` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'terms_conditions_view.php';
	$x->RedirectAfterInsert = 'terms_conditions_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Privacy policy';
	$x->TableIcon = 'resources/table_icons/text_horizontalrule.png';
	$x->PrimaryKey = '`terms_conditions`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Main head', 'Main head content', 'Sub head1', 'Head 1 Content', 'Sub head2', 'Head 2 content', 'Sub head3', 'Head 3 content', 'Sub head4', 'Head 4 content', ];
	$x->ColFieldName = ['main_head', 'main_head_content', 'sub_head1', 'head_1', 'sub_head2', 'head_2', 'sub_head3', 'head_3', 'sub_head4', 'head_4', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/terms_conditions_templateTV.html';
	$x->SelectedTemplate = 'templates/terms_conditions_templateTVS.html';
	$x->TemplateDV = 'templates/terms_conditions_templateDV.html';
	$x->TemplateDVP = 'templates/terms_conditions_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `terms_conditions`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='terms_conditions' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `terms_conditions`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='terms_conditions' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`terms_conditions`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: terms_conditions_init
	$render = true;
	if(function_exists('terms_conditions_init')) {
		$args = [];
		$render = terms_conditions_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: terms_conditions_header
	$headerCode = '';
	if(function_exists('terms_conditions_header')) {
		$args = [];
		$headerCode = terms_conditions_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: terms_conditions_footer
	$footerCode = '';
	if(function_exists('terms_conditions_footer')) {
		$args = [];
		$footerCode = terms_conditions_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
