<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/supplier.php");
	include_once("{$currDir}/supplier_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('supplier');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'supplier';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`supplier`.`id`" => "id",
		"`supplier`.`name`" => "name",
		"`supplier`.`shop_id`" => "shop_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`supplier`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`supplier`.`id`" => "id",
		"`supplier`.`name`" => "name",
		"`supplier`.`shop_id`" => "shop_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`supplier`.`id`" => "ID",
		"`supplier`.`name`" => "Name",
		"`supplier`.`shop_id`" => "Shop id",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`supplier`.`id`" => "id",
		"`supplier`.`name`" => "name",
		"`supplier`.`shop_id`" => "shop_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`supplier` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'supplier_view.php';
	$x->RedirectAfterInsert = 'supplier_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Supplier';
	$x->TableIcon = 'resources/table_icons/client_account_template.png';
	$x->PrimaryKey = '`supplier`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Name', 'Shop id', ];
	$x->ColFieldName = ['name', 'shop_id', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/supplier_templateTV.html';
	$x->SelectedTemplate = 'templates/supplier_templateTVS.html';
	$x->TemplateDV = 'templates/supplier_templateDV.html';
	$x->TemplateDVP = 'templates/supplier_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `supplier`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='supplier' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `supplier`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='supplier' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`supplier`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: supplier_init
	$render = true;
	if(function_exists('supplier_init')) {
		$args = [];
		$render = supplier_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: supplier_header
	$headerCode = '';
	if(function_exists('supplier_header')) {
		$args = [];
		$headerCode = supplier_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: supplier_footer
	$footerCode = '';
	if(function_exists('supplier_footer')) {
		$args = [];
		$footerCode = supplier_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
