<?php

// Data functions (insert, update, delete, form) for table system_setting

// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

function system_setting_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('system_setting');
	if(!$arrPerm['insert']) return false;

	$data = [
		'flash_sale' => Request::val('flash_sale', ''),
		'date' => Request::dateComponents('date', ''),
		'just_sold' => Request::val('just_sold', ''),
		'js_date' => Request::dateComponents('js_date', ''),
		'recommended' => Request::val('recommended', ''),
		'r_date' => Request::dateComponents('r_date', ''),
		'latest_product' => Request::val('latest_product', ''),
		'lp_date' => Request::dateComponents('lp_date', ''),
		'prods_1' => Request::val('prods_1', ''),
		'p1_date' => Request::dateComponents('p1_date', ''),
		'id' => Request::val('id', ''),
		'prods_2' => Request::val('prods_2', ''),
		'p2_date' => Request::dateComponents('p2_date', ''),
		'prods_3' => Request::val('prods_3', ''),
		'p3_date' => Request::dateComponents('p3_date', ''),
		'location' => Request::val('location', ''),
		'phone' => Request::val('phone', ''),
		'email' => Request::val('email', ''),
		'system_bg' => Request::val('system_bg', ''),
		'hidder' => Request::val('hidder', ''),
		'unhidder' => Request::val('unhidder', ''),
		'new_script' => Request::val('new_script', ''),
		'new_script2' => Request::val('new_script2', ''),
		'new_script3' => Request::val('new_script3', ''),
		'new_script4' => Request::val('new_script4', ''),
		'new_script5' => Request::val('new_script5', ''),
		'new_script6' => Request::val('new_script6', ''),
		'new_script7' => Request::val('new_script7', ''),
		'new_script8' => Request::val('new_script8', ''),
	];

	if($data['id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: system_setting_before_insert
	if(function_exists('system_setting_before_insert')) {
		$args = [];
		if(!system_setting_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('system_setting', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = $data['id'];

	update_calc_fields('system_setting', $recID, calculated_fields()['system_setting']);

	// hook: system_setting_after_insert
	if(function_exists('system_setting_after_insert')) {
		$res = sql("SELECT * FROM `system_setting` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!system_setting_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('system_setting', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) system_setting_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function system_setting_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function system_setting_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('system_setting', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: system_setting_before_delete
	if(function_exists('system_setting_before_delete')) {
		$args = [];
		if(!system_setting_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `system_setting` WHERE `id`='{$selected_id}'", $eo);

	// hook: system_setting_after_delete
	if(function_exists('system_setting_after_delete')) {
		$args = [];
		system_setting_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='system_setting' AND `pkValue`='{$selected_id}'", $eo);
}

function system_setting_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('system_setting', $selected_id, 'edit')) return false;

	$data = [
		'flash_sale' => Request::val('flash_sale', ''),
		'date' => Request::dateComponents('date', ''),
		'just_sold' => Request::val('just_sold', ''),
		'js_date' => Request::dateComponents('js_date', ''),
		'recommended' => Request::val('recommended', ''),
		'r_date' => Request::dateComponents('r_date', ''),
		'latest_product' => Request::val('latest_product', ''),
		'lp_date' => Request::dateComponents('lp_date', ''),
		'prods_1' => Request::val('prods_1', ''),
		'p1_date' => Request::dateComponents('p1_date', ''),
		'id' => Request::val('id', ''),
		'prods_2' => Request::val('prods_2', ''),
		'p2_date' => Request::dateComponents('p2_date', ''),
		'prods_3' => Request::val('prods_3', ''),
		'p3_date' => Request::dateComponents('p3_date', ''),
		'location' => Request::val('location', ''),
		'phone' => Request::val('phone', ''),
		'email' => Request::val('email', ''),
		'system_bg' => Request::val('system_bg', ''),
		'hidder' => Request::val('hidder', ''),
		'unhidder' => Request::val('unhidder', ''),
		'new_script' => Request::val('new_script', ''),
		'new_script2' => Request::val('new_script2', ''),
		'new_script3' => Request::val('new_script3', ''),
		'new_script4' => Request::val('new_script4', ''),
		'new_script5' => Request::val('new_script5', ''),
		'new_script6' => Request::val('new_script6', ''),
		'new_script7' => Request::val('new_script7', ''),
		'new_script8' => Request::val('new_script8', ''),
	];

	if($data['id'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Id': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('system_setting', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: system_setting_before_update
	if(function_exists('system_setting_before_update')) {
		$args = ['old_data' => $old_data];
		if(!system_setting_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'system_setting', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="system_setting_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}

	$data['selectedID'] = $data['id'];
	$newID = $data['id'];

	$eo = ['silentErrors' => true];

	update_calc_fields('system_setting', $data['selectedID'], calculated_fields()['system_setting']);

	// hook: system_setting_after_update
	if(function_exists('system_setting_after_update')) {
		$res = sql("SELECT * FROM `system_setting` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!system_setting_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "', `pkValue`='{$data['id']}' WHERE `tableName`='system_setting' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);

	// if PK value changed, update $selected_id
	$selected_id = $newID;
}

function system_setting_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('system_setting');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('', '');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: js_date
	$combo_js_date = new DateCombo;
	$combo_js_date->DateFormat = "mdy";
	$combo_js_date->MinYear = 1900;
	$combo_js_date->MaxYear = 2100;
	$combo_js_date->DefaultDate = parseMySQLDate('', '');
	$combo_js_date->MonthNames = $Translation['month names'];
	$combo_js_date->NamePrefix = 'js_date';
	// combobox: r_date
	$combo_r_date = new DateCombo;
	$combo_r_date->DateFormat = "mdy";
	$combo_r_date->MinYear = 1900;
	$combo_r_date->MaxYear = 2100;
	$combo_r_date->DefaultDate = parseMySQLDate('', '');
	$combo_r_date->MonthNames = $Translation['month names'];
	$combo_r_date->NamePrefix = 'r_date';
	// combobox: lp_date
	$combo_lp_date = new DateCombo;
	$combo_lp_date->DateFormat = "mdy";
	$combo_lp_date->MinYear = 1900;
	$combo_lp_date->MaxYear = 2100;
	$combo_lp_date->DefaultDate = parseMySQLDate('', '');
	$combo_lp_date->MonthNames = $Translation['month names'];
	$combo_lp_date->NamePrefix = 'lp_date';
	// combobox: p1_date
	$combo_p1_date = new DateCombo;
	$combo_p1_date->DateFormat = "mdy";
	$combo_p1_date->MinYear = 1900;
	$combo_p1_date->MaxYear = 2100;
	$combo_p1_date->DefaultDate = parseMySQLDate('', '');
	$combo_p1_date->MonthNames = $Translation['month names'];
	$combo_p1_date->NamePrefix = 'p1_date';
	// combobox: p2_date
	$combo_p2_date = new DateCombo;
	$combo_p2_date->DateFormat = "mdy";
	$combo_p2_date->MinYear = 1900;
	$combo_p2_date->MaxYear = 2100;
	$combo_p2_date->DefaultDate = parseMySQLDate('', '');
	$combo_p2_date->MonthNames = $Translation['month names'];
	$combo_p2_date->NamePrefix = 'p2_date';
	// combobox: p3_date
	$combo_p3_date = new DateCombo;
	$combo_p3_date->DateFormat = "mdy";
	$combo_p3_date->MinYear = 1900;
	$combo_p3_date->MaxYear = 2100;
	$combo_p3_date->DefaultDate = parseMySQLDate('', '');
	$combo_p3_date->MonthNames = $Translation['month names'];
	$combo_p3_date->NamePrefix = 'p3_date';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='system_setting' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='system_setting' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `system_setting` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'system_setting_view.php', false);
		}
		$combo_date->DefaultDate = $row['date'];
		$combo_js_date->DefaultDate = $row['js_date'];
		$combo_r_date->DefaultDate = $row['r_date'];
		$combo_lp_date->DefaultDate = $row['lp_date'];
		$combo_p1_date->DefaultDate = $row['p1_date'];
		$combo_p2_date->DefaultDate = $row['p2_date'];
		$combo_p3_date->DefaultDate = $row['p3_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/system_setting_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/system_setting_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return system_setting_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return system_setting_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return system_setting_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#flash_sale').replaceWith('<div class=\"form-control-static\" id=\"flash_sale\">' + (jQuery('#flash_sale').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#just_sold').replaceWith('<div class=\"form-control-static\" id=\"just_sold\">' + (jQuery('#just_sold').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#js_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#js_dateDay, #js_dateMonth, #js_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#recommended').replaceWith('<div class=\"form-control-static\" id=\"recommended\">' + (jQuery('#recommended').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#r_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#r_dateDay, #r_dateMonth, #r_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#latest_product').replaceWith('<div class=\"form-control-static\" id=\"latest_product\">' + (jQuery('#latest_product').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#lp_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#lp_dateDay, #lp_dateMonth, #lp_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#prods_1').replaceWith('<div class=\"form-control-static\" id=\"prods_1\">' + (jQuery('#prods_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#p1_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#p1_dateDay, #p1_dateMonth, #p1_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id').replaceWith('<div class=\"form-control-static\" id=\"id\">' + (jQuery('#id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#prods_2').replaceWith('<div class=\"form-control-static\" id=\"prods_2\">' + (jQuery('#prods_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#p2_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#p2_dateDay, #p2_dateMonth, #p2_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#prods_3').replaceWith('<div class=\"form-control-static\" id=\"prods_3\">' + (jQuery('#prods_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#p3_date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#p3_dateDay, #p3_dateMonth, #p3_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#location').replaceWith('<div class=\"form-control-static\" id=\"location\">' + (jQuery('#location').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#phone').replaceWith('<div class=\"form-control-static\" id=\"phone\">' + (jQuery('#phone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#system_bg').replaceWith('<div class=\"form-control-static\" id=\"system_bg\">' + (jQuery('#system_bg').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#hidder').replaceWith('<div class=\"form-control-static\" id=\"hidder\">' + (jQuery('#hidder').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#unhidder').replaceWith('<div class=\"form-control-static\" id=\"unhidder\">' + (jQuery('#unhidder').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script').replaceWith('<div class=\"form-control-static\" id=\"new_script\">' + (jQuery('#new_script').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script2').replaceWith('<div class=\"form-control-static\" id=\"new_script2\">' + (jQuery('#new_script2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script3').replaceWith('<div class=\"form-control-static\" id=\"new_script3\">' + (jQuery('#new_script3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script4').replaceWith('<div class=\"form-control-static\" id=\"new_script4\">' + (jQuery('#new_script4').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script5').replaceWith('<div class=\"form-control-static\" id=\"new_script5\">' + (jQuery('#new_script5').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script6').replaceWith('<div class=\"form-control-static\" id=\"new_script6\">' + (jQuery('#new_script6').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script7').replaceWith('<div class=\"form-control-static\" id=\"new_script7\">' + (jQuery('#new_script7').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#new_script8').replaceWith('<div class=\"form-control-static\" id=\"new_script8\">' + (jQuery('#new_script8').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(js_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_js_date->GetHTML(true) . '</div>' : $combo_js_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(js_date)%%>', $combo_js_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(r_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_r_date->GetHTML(true) . '</div>' : $combo_r_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(r_date)%%>', $combo_r_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(lp_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_lp_date->GetHTML(true) . '</div>' : $combo_lp_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(lp_date)%%>', $combo_lp_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(p1_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_p1_date->GetHTML(true) . '</div>' : $combo_p1_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(p1_date)%%>', $combo_p1_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(p2_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_p2_date->GetHTML(true) . '</div>' : $combo_p2_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(p2_date)%%>', $combo_p2_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(p3_date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_p3_date->GetHTML(true) . '</div>' : $combo_p3_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(p3_date)%%>', $combo_p3_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(flash_sale)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(just_sold)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(js_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(recommended)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(r_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(latest_product)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(lp_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prods_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(p1_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prods_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(p2_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prods_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(p3_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(location)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(system_bg)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hidder)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(unhidder)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script4)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script5)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script6)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script7)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(new_script8)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(flash_sale)%%>', safe_html($urow['flash_sale']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(flash_sale)%%>', html_attr($row['flash_sale']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flash_sale)%%>', urlencode($urow['flash_sale']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(just_sold)%%>', safe_html($urow['just_sold']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(just_sold)%%>', html_attr($row['just_sold']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(just_sold)%%>', urlencode($urow['just_sold']), $templateCode);
		$templateCode = str_replace('<%%VALUE(js_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['js_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(js_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['js_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(recommended)%%>', safe_html($urow['recommended']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(recommended)%%>', html_attr($row['recommended']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended)%%>', urlencode($urow['recommended']), $templateCode);
		$templateCode = str_replace('<%%VALUE(r_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['r_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(r_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['r_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(latest_product)%%>', safe_html($urow['latest_product']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(latest_product)%%>', html_attr($row['latest_product']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(latest_product)%%>', urlencode($urow['latest_product']), $templateCode);
		$templateCode = str_replace('<%%VALUE(lp_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['lp_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lp_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['lp_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prods_1)%%>', safe_html($urow['prods_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prods_1)%%>', html_attr($row['prods_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_1)%%>', urlencode($urow['prods_1']), $templateCode);
		$templateCode = str_replace('<%%VALUE(p1_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['p1_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p1_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['p1_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prods_2)%%>', safe_html($urow['prods_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prods_2)%%>', html_attr($row['prods_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_2)%%>', urlencode($urow['prods_2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(p2_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['p2_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p2_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['p2_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prods_3)%%>', safe_html($urow['prods_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prods_3)%%>', html_attr($row['prods_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_3)%%>', urlencode($urow['prods_3']), $templateCode);
		$templateCode = str_replace('<%%VALUE(p3_date)%%>', @date('m/d/Y', @strtotime(html_attr($row['p3_date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p3_date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['p3_date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(location)%%>', safe_html($urow['location']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(location)%%>', html_attr($row['location']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(location)%%>', urlencode($urow['location']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone)%%>', safe_html($urow['phone']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone)%%>', html_attr($row['phone']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone)%%>', urlencode($urow['phone']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(system_bg)%%>', safe_html($urow['system_bg']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(system_bg)%%>', html_attr($row['system_bg']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(system_bg)%%>', urlencode($urow['system_bg']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hidder)%%>', safe_html($urow['hidder']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hidder)%%>', html_attr($row['hidder']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hidder)%%>', urlencode($urow['hidder']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(unhidder)%%>', safe_html($urow['unhidder']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(unhidder)%%>', html_attr($row['unhidder']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(unhidder)%%>', urlencode($urow['unhidder']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script)%%>', safe_html($urow['new_script']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script)%%>', html_attr($row['new_script']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script)%%>', urlencode($urow['new_script']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script2)%%>', safe_html($urow['new_script2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script2)%%>', html_attr($row['new_script2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script2)%%>', urlencode($urow['new_script2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script3)%%>', safe_html($urow['new_script3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script3)%%>', html_attr($row['new_script3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script3)%%>', urlencode($urow['new_script3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script4)%%>', safe_html($urow['new_script4']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script4)%%>', html_attr($row['new_script4']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script4)%%>', urlencode($urow['new_script4']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script5)%%>', safe_html($urow['new_script5']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script5)%%>', html_attr($row['new_script5']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script5)%%>', urlencode($urow['new_script5']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script6)%%>', safe_html($urow['new_script6']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script6)%%>', html_attr($row['new_script6']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script6)%%>', urlencode($urow['new_script6']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script7)%%>', safe_html($urow['new_script7']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script7)%%>', html_attr($row['new_script7']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script7)%%>', urlencode($urow['new_script7']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(new_script8)%%>', safe_html($urow['new_script8']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(new_script8)%%>', html_attr($row['new_script8']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script8)%%>', urlencode($urow['new_script8']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(flash_sale)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flash_sale)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(just_sold)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(just_sold)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(js_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(js_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(recommended)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(r_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(r_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(latest_product)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(latest_product)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(lp_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lp_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prods_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(p1_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p1_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prods_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(p2_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p2_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prods_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prods_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(p3_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(p3_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(location)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(location)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(system_bg)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(system_bg)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hidder)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hidder)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(unhidder)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(unhidder)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script4)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script4)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script5)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script5)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script6)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script6)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script7)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script7)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(new_script8)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(new_script8)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('system_setting');
	if($selected_id) {
		$jdata = get_joined_record('system_setting', $selected_id);
		if($jdata === false) $jdata = get_defaults('system_setting');
		$rdata = $row;
	}
	$templateCode .= loadView('system_setting-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: system_setting_dv
	if(function_exists('system_setting_dv')) {
		$args=[];
		system_setting_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}