<?php
// This script and data application were generated by AppGini 5.96
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/system_setting.php");
	include_once("{$currDir}/system_setting_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('system_setting');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'system_setting';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`system_setting`.`flash_sale`" => "flash_sale",
		"if(`system_setting`.`date`,date_format(`system_setting`.`date`,'%m/%d/%Y'),'')" => "date",
		"`system_setting`.`just_sold`" => "just_sold",
		"if(`system_setting`.`js_date`,date_format(`system_setting`.`js_date`,'%m/%d/%Y'),'')" => "js_date",
		"`system_setting`.`recommended`" => "recommended",
		"if(`system_setting`.`r_date`,date_format(`system_setting`.`r_date`,'%m/%d/%Y'),'')" => "r_date",
		"`system_setting`.`latest_product`" => "latest_product",
		"if(`system_setting`.`lp_date`,date_format(`system_setting`.`lp_date`,'%m/%d/%Y'),'')" => "lp_date",
		"`system_setting`.`prods_1`" => "prods_1",
		"if(`system_setting`.`p1_date`,date_format(`system_setting`.`p1_date`,'%m/%d/%Y'),'')" => "p1_date",
		"`system_setting`.`id`" => "id",
		"`system_setting`.`prods_2`" => "prods_2",
		"if(`system_setting`.`p2_date`,date_format(`system_setting`.`p2_date`,'%m/%d/%Y'),'')" => "p2_date",
		"`system_setting`.`prods_3`" => "prods_3",
		"if(`system_setting`.`p3_date`,date_format(`system_setting`.`p3_date`,'%m/%d/%Y'),'')" => "p3_date",
		"`system_setting`.`location`" => "location",
		"`system_setting`.`phone`" => "phone",
		"`system_setting`.`email`" => "email",
		"`system_setting`.`system_bg`" => "system_bg",
		"`system_setting`.`hidder`" => "hidder",
		"`system_setting`.`unhidder`" => "unhidder",
		"`system_setting`.`new_script`" => "new_script",
		"`system_setting`.`new_script2`" => "new_script2",
		"`system_setting`.`new_script3`" => "new_script3",
		"`system_setting`.`new_script4`" => "new_script4",
		"`system_setting`.`new_script5`" => "new_script5",
		"`system_setting`.`new_script6`" => "new_script6",
		"`system_setting`.`new_script7`" => "new_script7",
		"`system_setting`.`new_script8`" => "new_script8",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => '`system_setting`.`date`',
		3 => 3,
		4 => '`system_setting`.`js_date`',
		5 => 5,
		6 => '`system_setting`.`r_date`',
		7 => 7,
		8 => '`system_setting`.`lp_date`',
		9 => 9,
		10 => '`system_setting`.`p1_date`',
		11 => 11,
		12 => 12,
		13 => '`system_setting`.`p2_date`',
		14 => 14,
		15 => '`system_setting`.`p3_date`',
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => '`system_setting`.`hidder`',
		21 => '`system_setting`.`unhidder`',
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`system_setting`.`flash_sale`" => "flash_sale",
		"if(`system_setting`.`date`,date_format(`system_setting`.`date`,'%m/%d/%Y'),'')" => "date",
		"`system_setting`.`just_sold`" => "just_sold",
		"if(`system_setting`.`js_date`,date_format(`system_setting`.`js_date`,'%m/%d/%Y'),'')" => "js_date",
		"`system_setting`.`recommended`" => "recommended",
		"if(`system_setting`.`r_date`,date_format(`system_setting`.`r_date`,'%m/%d/%Y'),'')" => "r_date",
		"`system_setting`.`latest_product`" => "latest_product",
		"if(`system_setting`.`lp_date`,date_format(`system_setting`.`lp_date`,'%m/%d/%Y'),'')" => "lp_date",
		"`system_setting`.`prods_1`" => "prods_1",
		"if(`system_setting`.`p1_date`,date_format(`system_setting`.`p1_date`,'%m/%d/%Y'),'')" => "p1_date",
		"`system_setting`.`id`" => "id",
		"`system_setting`.`prods_2`" => "prods_2",
		"if(`system_setting`.`p2_date`,date_format(`system_setting`.`p2_date`,'%m/%d/%Y'),'')" => "p2_date",
		"`system_setting`.`prods_3`" => "prods_3",
		"if(`system_setting`.`p3_date`,date_format(`system_setting`.`p3_date`,'%m/%d/%Y'),'')" => "p3_date",
		"`system_setting`.`location`" => "location",
		"`system_setting`.`phone`" => "phone",
		"`system_setting`.`email`" => "email",
		"`system_setting`.`system_bg`" => "system_bg",
		"`system_setting`.`hidder`" => "hidder",
		"`system_setting`.`unhidder`" => "unhidder",
		"`system_setting`.`new_script`" => "new_script",
		"`system_setting`.`new_script2`" => "new_script2",
		"`system_setting`.`new_script3`" => "new_script3",
		"`system_setting`.`new_script4`" => "new_script4",
		"`system_setting`.`new_script5`" => "new_script5",
		"`system_setting`.`new_script6`" => "new_script6",
		"`system_setting`.`new_script7`" => "new_script7",
		"`system_setting`.`new_script8`" => "new_script8",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`system_setting`.`flash_sale`" => "Flash_sale",
		"`system_setting`.`date`" => "Date",
		"`system_setting`.`just_sold`" => "Just_sold",
		"`system_setting`.`js_date`" => "Js_date",
		"`system_setting`.`recommended`" => "Recommended",
		"`system_setting`.`r_date`" => "R_date",
		"`system_setting`.`latest_product`" => "Latest_product",
		"`system_setting`.`lp_date`" => "Lp_date",
		"`system_setting`.`prods_1`" => "Prods_1",
		"`system_setting`.`p1_date`" => "P1_date",
		"`system_setting`.`id`" => "Id",
		"`system_setting`.`prods_2`" => "Prods_2",
		"`system_setting`.`p2_date`" => "P2_date",
		"`system_setting`.`prods_3`" => "Prods_3",
		"`system_setting`.`p3_date`" => "P3_date",
		"`system_setting`.`location`" => "Location",
		"`system_setting`.`phone`" => "Phone",
		"`system_setting`.`email`" => "Email",
		"`system_setting`.`system_bg`" => "System_bg",
		"`system_setting`.`hidder`" => "Hidder",
		"`system_setting`.`unhidder`" => "Unhidder",
		"`system_setting`.`new_script`" => "New_script",
		"`system_setting`.`new_script2`" => "New_script2",
		"`system_setting`.`new_script3`" => "New_script3",
		"`system_setting`.`new_script4`" => "New_script4",
		"`system_setting`.`new_script5`" => "New_script5",
		"`system_setting`.`new_script6`" => "New_script6",
		"`system_setting`.`new_script7`" => "New_script7",
		"`system_setting`.`new_script8`" => "New_script8",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`system_setting`.`flash_sale`" => "flash_sale",
		"if(`system_setting`.`date`,date_format(`system_setting`.`date`,'%m/%d/%Y'),'')" => "date",
		"`system_setting`.`just_sold`" => "just_sold",
		"if(`system_setting`.`js_date`,date_format(`system_setting`.`js_date`,'%m/%d/%Y'),'')" => "js_date",
		"`system_setting`.`recommended`" => "recommended",
		"if(`system_setting`.`r_date`,date_format(`system_setting`.`r_date`,'%m/%d/%Y'),'')" => "r_date",
		"`system_setting`.`latest_product`" => "latest_product",
		"if(`system_setting`.`lp_date`,date_format(`system_setting`.`lp_date`,'%m/%d/%Y'),'')" => "lp_date",
		"`system_setting`.`prods_1`" => "prods_1",
		"if(`system_setting`.`p1_date`,date_format(`system_setting`.`p1_date`,'%m/%d/%Y'),'')" => "p1_date",
		"`system_setting`.`id`" => "id",
		"`system_setting`.`prods_2`" => "prods_2",
		"if(`system_setting`.`p2_date`,date_format(`system_setting`.`p2_date`,'%m/%d/%Y'),'')" => "p2_date",
		"`system_setting`.`prods_3`" => "prods_3",
		"if(`system_setting`.`p3_date`,date_format(`system_setting`.`p3_date`,'%m/%d/%Y'),'')" => "p3_date",
		"`system_setting`.`location`" => "location",
		"`system_setting`.`phone`" => "phone",
		"`system_setting`.`email`" => "email",
		"`system_setting`.`system_bg`" => "system_bg",
		"`system_setting`.`hidder`" => "hidder",
		"`system_setting`.`unhidder`" => "unhidder",
		"`system_setting`.`new_script`" => "new_script",
		"`system_setting`.`new_script2`" => "new_script2",
		"`system_setting`.`new_script3`" => "new_script3",
		"`system_setting`.`new_script4`" => "new_script4",
		"`system_setting`.`new_script5`" => "new_script5",
		"`system_setting`.`new_script6`" => "new_script6",
		"`system_setting`.`new_script7`" => "new_script7",
		"`system_setting`.`new_script8`" => "new_script8",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`system_setting` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'system_setting_view.php';
	$x->RedirectAfterInsert = 'system_setting_view.php';
	$x->TableTitle = 'System_setting';
	$x->TableIcon = 'resources/table_icons/table.png';
	$x->PrimaryKey = '`system_setting`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Flash_sale', 'Date', 'Just_sold', 'Js_date', 'Recommended', 'R_date', 'Latest_product', 'Lp_date', 'Prods_1', 'P1_date', 'Id', 'Prods_2', 'P2_date', 'Prods_3', 'P3_date', 'Location', 'Phone', 'Email', 'System_bg', 'Hidder', 'Unhidder', 'New_script', 'New_script2', 'New_script3', 'New_script4', 'New_script5', 'New_script6', 'New_script7', 'New_script8', ];
	$x->ColFieldName = ['flash_sale', 'date', 'just_sold', 'js_date', 'recommended', 'r_date', 'latest_product', 'lp_date', 'prods_1', 'p1_date', 'id', 'prods_2', 'p2_date', 'prods_3', 'p3_date', 'location', 'phone', 'email', 'system_bg', 'hidder', 'unhidder', 'new_script', 'new_script2', 'new_script3', 'new_script4', 'new_script5', 'new_script6', 'new_script7', 'new_script8', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/system_setting_templateTV.html';
	$x->SelectedTemplate = 'templates/system_setting_templateTVS.html';
	$x->TemplateDV = 'templates/system_setting_templateDV.html';
	$x->TemplateDVP = 'templates/system_setting_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `system_setting`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='system_setting' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `system_setting`.`id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='system_setting' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`system_setting`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: system_setting_init
	$render = true;
	if(function_exists('system_setting_init')) {
		$args = [];
		$render = system_setting_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: system_setting_header
	$headerCode = '';
	if(function_exists('system_setting_header')) {
		$args = [];
		$headerCode = system_setting_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: system_setting_footer
	$footerCode = '';
	if(function_exists('system_setting_footer')) {
		$args = [];
		$footerCode = system_setting_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
